# Generated by Django 5.2.11 on 2026-02-28 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_remove_job_services'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Snapshot of price at time of booking', max_digits=8)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_services', to='jobs.job')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_services', to='services.service')),
            ],
            options={
                'unique_together': {('job', 'service')},
            },
        ),
    ]
