# Generated by Django 5.2.11 on 2026-02-28 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_remove_job_services'),
        ('services', '0002_jobservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='service',
            field=models.ManyToManyField(blank=True, through='services.JobService', to='services.service'),
        ),
    ]
