# Generated by Django 5.2.11 on 2026-02-28 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='service',
            new_name='services',
        ),
    ]
